github:
  description: "Apache Camel K runtime"
  homepage: https://camel.apache.org
  labels:
    - camel
    - integration
    - kubernetes
    - serverless
    - knative
    - openshift
    - operator
  enabled_merge_buttons:
    merge: false
    rebase: true
    squash: true