Apache Camel K Runtime
======================

image:https://img.shields.io/maven-central/v/org.apache.camel.k/camel-k-runtime-bom.svg["Maven Central", link="http://search.maven.org/#search%7Cga%7C1%7Corg.apache.camel.k"]
image:https://img.shields.io/github/license/openshift/origin.svg?maxAge=2592000["Licensed under Apache License version 2.0", link="https://www.apache.org/licenses/LICENSE-2.0"]
image:https://img.shields.io/badge/zulip-join_chat-brightgreen.svg["Chat on Zulip", link="https://camel.zulipchat.com"]
image:https://github.com/apache/camel-k-runtime/workflows/Build/badge.svg["Build Status", link="https://github.com/apache/camel-k-runtime/actions?query=workflow%3ABuild"]

This repository contains the Apache Camel-K Runtime bits used by the https://github.com/apache/camel-k[ Camel K project_]. This is a lightweight dependency used on top of Camel Quarkus, required by Camel K operator to set all the runtime configuration on Kubernetes.

== How to bump the main dependencies

In order to simplify the maintenance, you can use a script in `/script/` directory which take care of bumping the versions for the project, aligning it with Camel Quarkus version: `./scripts/bump.sh --camel-quarkus 2.16.0`. When starting a new major or minor release, you'll also need to align the dependencies expected by Camel Quarkus running `./scripts/sync_cq.sh --skip-version-check`.

The project has an automatic action (`./scripts/sync_cq.sh`) running every night by Github Actions which is in charge to align the set of dependencies required by Camel Quarkus, according to the release. This is useful to keep up to date each patch release.

== Instructions for local debugging

You can https://camel.apache.org/camel-k/latest/contributing/local-development.html#_local_camel_k_runtime[follow these instructions] in order to run and debug a Camel K integration based on a local Camel K runtime.
