Apache Camel K Runtime
======================

image:https://img.shields.io/maven-central/v/org.apache.camel.k/camel-k-runtime-bom.svg["Maven Central", link="http://search.maven.org/#search%7Cga%7C1%7Corg.apache.camel.k"]
image:https://img.shields.io/github/license/openshift/origin.svg?maxAge=2592000["Licensed under Apache License version 2.0", link="https://www.apache.org/licenses/LICENSE-2.0"]
image:https://img.shields.io/badge/zulip-join_chat-brightgreen.svg["Chat on Zulip", link="https://camel.zulipchat.com"]
image:https://github.com/apache/camel-k-runtime/workflows/Build/badge.svg["Build Status", link="https://github.com/apache/camel-k-runtime/actions?query=workflow%3ABuild"]

This repository contains the Apache Camel-K Runtime bits used by the https://github.com/apache/camel-k[_main project_]

== How to bump the main dependencies

In order to simplify the maintenance, you can use a script in `/script/` directory which take care of bumping the versions for the project. As we maintain a BOM which is not inheriting the main project parent, this is very handy to keep versions aligned. Instructions how to run the script:
....
Usage: ./script/bump.sh [options]
--version                 Bump Camel K runtime version
--camel                   Bump Camel version
--camel-quarkus           Bump Camel-Quarkus version
--quarkus                 Bump Quarkus version
--graalvm                 Bump GraalVM version
--help                    This help message

Example: ./script/bump.sh --version 3.20.1-SNAPSHOT --camel 3.20.1
....

NOTE: starting from version 3.20, Camel K Runtime will need to use the same dependency notation of Camel.

== Instructions for local debugging

You can https://camel.apache.org/camel-k/latest/contributing/local-development.html#_local_camel_k_runtime[follow these instructions] in order to run and debug a Camel K integration based on a local Camel K runtime.
